### ISSUE TITLE
`Ctrl + C` killing doesn't seem to close rsync connection

### ISSUE THREAD

**Issue by bartkl** [bartkl/backup#8]
```
^CTraceback (most recent call last):
  File "/usr/local/bin/backup", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/dist-packages/backup/__init__.py", line 96, in cli
    backup.backup_modules(*sys.argv[1:])
  File "/usr/local/lib/python3.9/dist-packages/backup/__init__.py", line 73, in backup_modules
    retcode = self.backup_module(module, dry)
  File "/usr/local/lib/python3.9/dist-packages/backup/__init__.py", line 59, in backup_module
    result = subprocess.run(rsync_cmd)
  File "/usr/lib/python3.9/subprocess.py", line 507, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.9/subprocess.py", line 1126, in communicate
    self.wait()
  File "/usr/lib/python3.9/subprocess.py", line 1189, in wait
    return self._wait(timeout=timeout)
  File "/usr/lib/python3.9/subprocess.py", line 1919, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.9/subprocess.py", line 1877, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt

bart@terminus:~ $ backup stuff
Backing up module stuff...
rsync --itemize-changes --verbose --archive --update --delete --password-file=<PWD_FILE> --partial --inplace /path/stuff/ <HOST>::stuff
Running rsync...
@ERROR: max connections (1) reached -- try again later
rsync error: error starting client-server protocol (code 5) at main.c(1817) [sender=3.2.3]

Backup for module `stuff` failed with exit code 5.

Backup failed for module `stuff`. Rsync exited with exit code 5.

```

**Comment by bartkl** [comment]
I think this has been fixed.
